import './globals.css'
import {Noto_Sans} from 'next/font/google'

export const metadata = {
  title: 'Signup',
  description: 'Generated by create next app',
}

const noto = Noto_Sans({
  weight:['300','400','500','600','700'],
  subsets:['latin']
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={noto.className}>{children}</body>
    </html>
  )
}
